package com.pellegrinoprincipe;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

public class QueryForm extends javax.swing.JFrame
{
    // nome dei campi delle tabelle del database articoli
    private String table_fields[][] =
    {
        {
            "id_articolo", "rivista", "titolo", "pagina", "genere", "autore"
        },
        {
            "id_autore", "nome", "cognome", "indirizzo", "citta", "telefono", "email", "professione", "foto"
        },
        {
            "id_genere", "descrizione"
        },
        {
            "id_rivista", "nome", "editore", "nr", "copertina"
        }
    };

    public QueryForm()
    {
        initComponents();

        // effettuo la connessione al databse;
        connectionToDatabase();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_selectTable = new javax.swing.JComboBox();
        panel_for_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_to_show = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QueryForm");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selezione:"));

        jLabel1.setText("Tabella da interrogare:");

        cb_selectTable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "articolo", "autore", "genere", "rivista" }));
        cb_selectTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_selectTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_selectTable, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_selectTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_for_table.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultset:"));

        table_to_show.setModel(new DefaultTableModel());
        jScrollPane1.setViewportView(table_to_show);

        javax.swing.GroupLayout panel_for_tableLayout = new javax.swing.GroupLayout(panel_for_table);
        panel_for_table.setLayout(panel_for_tableLayout);
        panel_for_tableLayout.setHorizontalGroup(
            panel_for_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_for_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_for_tableLayout.setVerticalGroup(
            panel_for_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_for_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output:"));

        ta_result.setColumns(20);
        ta_result.setRows(5);
        jScrollPane2.setViewportView(ta_result);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_for_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_for_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void cb_selectTableActionPerformed(java.awt.event.ActionEvent evt)                                               
    {                                                   
        // ottengo quale item è stato selezionato, il suo valore
        // e costruisco la query
        JComboBox cb = (JComboBox) evt.getSource();
        String table = (String) cb.getSelectedItem();
        int ix = cb.getSelectedIndex();

        String query = "SELECT * FROM " + table;

        ResultSet rs = DBHelper_REV_1.doQuery(query);

        try
        {
            // numero di righe
            int nr_row = rs.last() ? rs.getRow() : 0;
            rs.beforeFirst();

            if (nr_row > 0)
            {
                Object data[][] = new Object[nr_row][];

                // numero di colonne della riga
                int col_nr = table_fields[ix].length;

                // ottengo i dati
                while (rs.next())
                {
                    int row = rs.getRow();

                    data[row - 1] = new Object[col_nr];

                    // popolo la matrice con i valori delle colonne
                    // di una riga
                    for (int i = 0; i < col_nr; i++)
                    {
                        data[row - 1][i] = rs.getString(i + 1);
                    }
                }

                // popola la tabella
                table_to_show.setModel(new DefaultTableModel(data, table_fields[ix]));
                ta_result.setText("Query eseguita con successo!!!");
            }
        }
        catch (SQLException ex)
        {
            ta_result.setText(ex.getMessage());
        }
    }                                              

    private void connectionToDatabase()
    {
        DBHelper_REV_1.dbtype = "MySQL";
        DBHelper_REV_1.output = ta_result;
        DBHelper_REV_1.loadDriver();
        DBHelper_REV_1.doConnection("localhost", "3306", "articoli", "java8", "java8");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new QueryForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JComboBox cb_selectTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_for_table;
    private javax.swing.JTextArea ta_result;
    private javax.swing.JTable table_to_show;
    // End of variables declaration                   
}
