package com.pellegrinoprincipe;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

public class NavigatorForm extends javax.swing.JFrame
{
    private ImageIcon prev_icon;
    private ImageIcon prev_dis_icon;
    private ImageIcon next_icon;
    private ImageIcon next_dis_icon;
    private ImageIcon last_icon;
    private ImageIcon last_dis_icon;
    private ImageIcon first_icon;
    private ImageIcon first_dis_icon;
    private ResultSet rs;
    private int nr_row;

    public NavigatorForm()
    {
        initComponents();

        // carica le icone del navigatore
        loadIcons();

        // effettuo la connessione al databse;
        connectionToDatabase();

        txt_go_record.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_desc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_first = new javax.swing.JLabel();
        lbl_prev = new javax.swing.JLabel();
        lbl_next = new javax.swing.JLabel();
        lbl_last = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_go_record = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_tot_record = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NavigatorForm");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabella genere:"));

        jLabel1.setText("id_genere:");

        txt_id.setEditable(false);

        jLabel2.setText("descrizione:");

        txt_desc.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_desc, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigatore:"));

        lbl_first.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if(rs != null)
                        lbl_firstMouseClicked(evt);
            }
        });

        lbl_prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                   if(rs != null)
                       lbl_prevMouseClicked(evt);
            }
        });

        lbl_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {                
                   if(rs != null)
                       lbl_nextMouseClicked(evt);
            }
        });

        lbl_last.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                   if(rs != null)
                       lbl_lastMouseClicked(evt);
            }
        });

        jLabel3.setText("Vai al record nr.:");

        txt_go_record.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_go_recordFocusLost(evt);
            }
        });

        jLabel4.setText("Tot. record:");

        lbl_tot_record.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_first)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_prev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_next)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_last)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tot_record))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_go_record, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_first)
                            .addComponent(lbl_prev)
                            .addComponent(lbl_next)
                            .addComponent(lbl_last)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_go_record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_tot_record)))
        );

        btn_start.setText("Avvia...");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output:"));

        ta_result.setColumns(20);
        ta_result.setRows(5);
        jScrollPane1.setViewportView(ta_result);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_start))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_start)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt)                                          
    {                                              
        txt_go_record.setEnabled(true);        
        String query = "SELECT * FROM genere";
        
        rs = DBHelper_REV_2.doQuery(query, true); // resultset full navigable

        try
        {
            // numero di righe
            nr_row = rs.last() ? rs.getRow() : 0;
            rs.beforeFirst();
            lbl_tot_record.setText("1 di " + nr_row);

            if (nr_row > 0)
            {                
                if (rs.next()) // primo record
                {
                    txt_id.setText(rs.getString(1));
                    txt_desc.setText(rs.getString(2));
                }                
                if (nr_row > 1) // attivo i pulsanti navigatore
                {
                    lbl_next.setIcon(next_icon);
                    lbl_last.setIcon(last_icon);
                }
            }
        }
        catch (SQLException ex) { ta_result.setText(ex.getMessage()); }
    }                                         

    private void lbl_lastMouseClicked(java.awt.event.MouseEvent evt)                                      
    {                                          
        try
        {      
            rs.last(); // sposto il cursore all'ultimo record

            txt_id.setText(rs.getString(1));
            txt_desc.setText(rs.getString(2));

            // navigatore
            lbl_next.setIcon(next_dis_icon);
            lbl_last.setIcon(last_dis_icon);
            lbl_prev.setIcon(prev_icon);
            lbl_first.setIcon(first_icon);

            lbl_tot_record.setText(rs.getRow() + " di " + nr_row);
            
        }
        catch (SQLException ex) { ta_result.setText(ex.getMessage()); }
    }                                     

    private void lbl_firstMouseClicked(java.awt.event.MouseEvent evt)                                       
    {                                           
        try
        {            
            rs.first(); // sposto il cursore al primo record

            txt_id.setText(rs.getString(1));
            txt_desc.setText(rs.getString(2));

            // navigatore
            lbl_next.setIcon(next_icon);
            lbl_last.setIcon(last_icon);
            lbl_prev.setIcon(prev_dis_icon);
            lbl_first.setIcon(first_dis_icon);

            lbl_tot_record.setText(rs.getRow() + " di " + nr_row);
        }
        catch (SQLException ex) { ta_result.setText(ex.getMessage()); }
    }                                      

    private void lbl_nextMouseClicked(java.awt.event.MouseEvent evt)                                      
    {                                          
        try
        {           
            boolean row = rs.relative(1); // sposto il cursore al successivo record

            if (row) // se lo spostamento ha trovato un record...
            {
                txt_id.setText(rs.getString(1));
                txt_desc.setText(rs.getString(2));

                if (rs.isLast()) // navigatore
                {
                    lbl_next.setIcon(next_dis_icon);
                    lbl_last.setIcon(last_dis_icon);
                }
                else
                {
                    lbl_next.setIcon(next_icon);
                    lbl_last.setIcon(last_icon);
                }

                lbl_prev.setIcon(prev_icon);
                lbl_first.setIcon(first_icon);
            }
            else
                rs.last();

            lbl_tot_record.setText(rs.getRow() + " di " + nr_row);            

        }
        catch (SQLException ex) { ta_result.setText(ex.getMessage()); }
    }                                     

    private void lbl_prevMouseClicked(java.awt.event.MouseEvent evt)                                      
    {                                          
        try
        {            
            boolean row = rs.relative(-1); // sposto il cursore al precedente record
            
            if (row) // se lo spostamento ha trovato un record...
            {
                txt_id.setText(rs.getString(1));
                txt_desc.setText(rs.getString(2));
                
                if (rs.isFirst()) // navigatore
                {
                    lbl_prev.setIcon(prev_dis_icon);
                    lbl_first.setIcon(first_dis_icon);
                }
                else
                {
                    lbl_prev.setIcon(prev_icon);
                    lbl_first.setIcon(first_icon);
                }

                lbl_next.setIcon(next_icon);
                lbl_last.setIcon(last_icon);
            }
            else
                rs.first();
  
            lbl_tot_record.setText(rs.getRow() + " di " + nr_row);
        }
        catch (SQLException ex) { ta_result.setText(ex.getMessage()); }
    }                                     

    private void txt_go_recordFocusLost(java.awt.event.FocusEvent evt)                                        
    {                                            
        int pos = Integer.valueOf(txt_go_record.getText());

        try
        {            
            rs.absolute(pos); // spostamento assoluto

            txt_id.setText(rs.getString(1));
            txt_desc.setText(rs.getString(2));
            
            if (rs.isFirst()) // navigatore
            {
                lbl_prev.setIcon(prev_dis_icon);
                lbl_first.setIcon(first_dis_icon);
            }
            else if (rs.isLast())
            {
                lbl_next.setIcon(next_dis_icon);
                lbl_last.setIcon(last_dis_icon);
            }
            else
            {
                lbl_prev.setIcon(prev_icon);
                lbl_first.setIcon(first_icon);
                lbl_next.setIcon(next_icon);
                lbl_last.setIcon(last_icon);
            }

            lbl_tot_record.setText(rs.getRow() + " di " + nr_row);
        }
        catch (SQLException ex) { ta_result.setText(ex.getMessage()); }
    }                                       

    private void loadIcons()
    {
        // icone
        first_icon = new ImageIcon(getClass().getResource("nav_first.png"));
        first_dis_icon = new ImageIcon(getClass().getResource("nav_first_dis.png"));
        last_icon = new ImageIcon(getClass().getResource("nav_last.png"));
        last_dis_icon = new ImageIcon(getClass().getResource("nav_last_dis.png"));
        next_icon = new ImageIcon(getClass().getResource("nav_next.png"));
        next_dis_icon = new ImageIcon(getClass().getResource("nav_next_dis.png"));
        prev_icon = new ImageIcon(getClass().getResource("nav_prev.png"));
        prev_dis_icon = new ImageIcon(getClass().getResource("nav_prev_dis.png"));

        lbl_first.setIcon(first_dis_icon);
        lbl_prev.setIcon(prev_dis_icon);
        lbl_next.setIcon(next_dis_icon);
        lbl_last.setIcon(last_dis_icon);
    }

    private void connectionToDatabase()
    {
        DBHelper_REV_2.dbtype = "MySQL";
        DBHelper_REV_2.output = ta_result;
        DBHelper_REV_2.loadDriver();
        DBHelper_REV_2.doConnection("localhost", "3306", "articoli", "java8", "java8");
    }

    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new NavigatorForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_first;
    private javax.swing.JLabel lbl_last;
    private javax.swing.JLabel lbl_next;
    private javax.swing.JLabel lbl_prev;
    private javax.swing.JLabel lbl_tot_record;
    private javax.swing.JTextArea ta_result;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_go_record;
    private javax.swing.JTextField txt_id;
    // End of variables declaration                   
}
