package com.pellegrinoprincipe;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JComboBox;

public class StoredProcedureForm extends javax.swing.JFrame
{
    private CallableStatement cs;
    private String procedures_def[] =
    {
        "PROCEDURE showConnectedUser(OUT cu varchar(50), INOUT tt datetime)\n"
        + "BEGIN\n"
        + "-- leggo la data attuale di richiesta\n"
        + "SELECT tt;\n"
        + "\n"
        + "/*\n"
        + "ne imposto una nuova\n"
        + "*/\n"
        + "SET tt = NOW();\n"
        + "\n"
        + "-- utente connesso\n"
        + "SELECT CURRENT_USER() INTO cu;\n"
        + "END"
    };

    public StoredProcedureForm()
    {
        initComponents();

        // effettuo la connessione al databse;
        connectionToDatabase();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_selectTable = new javax.swing.JComboBox();
        panel_for_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_sdef = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StoredProcedureForm");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selezione:"));

        jLabel1.setText("Stored Procedure da eseguire:");

        cb_selectTable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "showConnectedUser" }));
        cb_selectTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_selectTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_selectTable, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_selectTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_for_table.setBorder(javax.swing.BorderFactory.createTitledBorder("Definizione:"));

        ta_sdef.setColumns(20);
        ta_sdef.setEditable(false);
        ta_sdef.setFont(new java.awt.Font("Monospaced", 1, 9));
        ta_sdef.setRows(5);
        ta_sdef.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        ta_sdef.setEnabled(false);
        jScrollPane1.setViewportView(ta_sdef);

        javax.swing.GroupLayout panel_for_tableLayout = new javax.swing.GroupLayout(panel_for_table);
        panel_for_table.setLayout(panel_for_tableLayout);
        panel_for_tableLayout.setHorizontalGroup(
            panel_for_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_for_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_for_tableLayout.setVerticalGroup(
            panel_for_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_for_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output:"));

        ta_result.setColumns(20);
        ta_result.setRows(5);
        jScrollPane2.setViewportView(ta_result);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_for_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_for_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void cb_selectTableActionPerformed(java.awt.event.ActionEvent evt)                                               
    {                                                   
        // ottengo quale item è stato selezionato, il suo valore
        // e costruisco la query
        JComboBox cb = (JComboBox) evt.getSource();
        String s_procedure = (String) cb.getSelectedItem();
        int ix = cb.getSelectedIndex();
        
        ta_sdef.setText(procedures_def[ix]);
        
        // ottengo un oggetto CallableStatement
        String procedure = "{CALL " + s_procedure + "(?, ?)}";
        cs = DBHelper_REV_4.getCallableStatement(procedure, false);

        // variabili che conterranno i valori ritornati dalla procedura
        String us = "none";
        Date t = new Date();

        try
        {
            // registro il parametro di tipo OUT
            cs.registerOutParameter(1, java.sql.Types.VARCHAR);

            // registro il parametro di tipo INOUT
            cs.setDate(2, new java.sql.Date(t.getTime()));
            cs.registerOutParameter(2, java.sql.Types.DATE);
            
            cs.execute(); // eseguo la store

            // utente e ora
            us = cs.getString(1);
            t =  new Date(cs.getTimestamp(2).getTime());

            ta_result.setText(us + "\n" + t);
        }
        catch (SQLException ex) { ta_result.setText(ex.getMessage()); }
    }                                              

    private void connectionToDatabase()
    {
        DBHelper_REV_4.dbtype = "MySQL";
        DBHelper_REV_4.output = ta_result;
        DBHelper_REV_4.loadDriver();
        DBHelper_REV_4.doConnection("localhost", "3306", "articoli", "java8", "java8");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new StoredProcedureForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JComboBox cb_selectTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_for_table;
    private javax.swing.JTextArea ta_result;
    private javax.swing.JTextArea ta_sdef;
    // End of variables declaration
}
